const account = `
CREATE TABLE IF NOT EXISTS account (
  id CHARACTER VARYING PRIMARY KEY NOT NULL,
  username CHARACTER VARYING NOT NULL,
  password CHARACTER VARYING NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT false,
  createdat TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updatedat TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)`;

const tag = `
CREATE TABLE IF NOT EXISTS tag (
  id CHARACTER VARYING PRIMARY KEY NOT NULL,
  title CHARACTER VARYING NOT NULL,
  accountid CHARACTER VARYING REFERENCES account(id),
  deleted BOOLEAN NOT NULL DEFAULT false,
  createdat TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updatedat TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)`;

const note = `
CREATE TABLE IF NOT EXISTS note (
  id CHARACTER VARYING PRIMARY KEY NOT NULL,
  content CHARACTER VARYING NOT NULL,
  accountid CHARACTER VARYING REFERENCES account(id),
  deleted BOOLEAN NOT NULL DEFAULT false,
  createdat TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updatedat TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)`;


const sticker = `
CREATE TABLE IF NOT EXISTS sticker (
  id CHARACTER VARYING PRIMARY KEY NOT NULL,
  tagid CHARACTER VARYING REFERENCES tag(id),
  noteid CHARACTER VARYING REFERENCES note(id),
  accountid CHARACTER VARYING REFERENCES account(id),
  deleted BOOLEAN NOT NULL DEFAULT false,
  createdat TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updatedat TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)`;

module.exports = [
  account,
  tag,
  note,
  sticker
];
